import { Handler } from "@netlify/functions";
import { createClient } from "@supabase/supabase-js";

// Supabase client with service role
const supabase = createClient(
  process.env.SUPABASE_URL as string,
  process.env.SUPABASE_SERVICE_ROLE_KEY as string
);

/**
 * POST /.netlify/functions/createUser
 * Body: { username: string, password: string }
 * 
 * The e‑mail is autogenerated as `${username}@example.com`
 */
export const handler: Handler = async (event, _context) => {
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, body: "Method Not Allowed" };
  }

  try {
    const { username, password } = JSON.parse(event.body || "{}");

    if (!username || !password) {
      return { statusCode: 400, body: "Missing username or password" };
    }

    // Supabase still requires a valid, unique e‑mail: generate one on the fly
    const email = `${username}@example.com`;

    // Call Supabase Admin API
    const { data: user, error } = await supabase.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: { username },
    });

    if (error) {
      console.error("Supabase createUser error:", error);
      return {
        statusCode: 400,
        body: error.message || "Supabase createUser failed",
      };
    }

    // Success
    return {
      statusCode: 200,
      body: JSON.stringify({ success: true, user }),
    };
  } catch (err: any) {
    console.error("Unhandled createUser error:", err);
    return { statusCode: 500, body: "Internal server error" };
  }
};