steps:
  # Step 1: Build Docker image with secrets as build args
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg VITE_CLERK_PUBLISHABLE_KEY=$$VITE_CLERK_PUBLISHABLE_KEY \
          --build-arg VITE_MASTER_ADMIN_ID=${_VITE_MASTER_ADMIN_ID:-} \
          -t ${_IMAGE_NAME} .
    secretEnv:
      - 'VITE_CLERK_PUBLISHABLE_KEY'

  # Step 2: Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/CLERK_PUBLISHABLE_KEY/versions/latest
      env: 'VITE_CLERK_PUBLISHABLE_KEY'

substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/vega-tenant-api'
  _BRANCH: 'main'
  _VITE_MASTER_ADMIN_ID: ''

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
