steps:
  # Step 1: Build Docker image
  # Note: Cloud Build resolves substitutions before passing to bash
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit on error
        echo "DEBUG: Checking substitution..."
        echo "DEBUG: _VITE_CLERK_PUBLISHABLE_KEY is set: $([ -n "${_VITE_CLERK_PUBLISHABLE_KEY}" ] && echo 'YES' || echo 'NO')"
        echo "DEBUG: _VITE_CLERK_PUBLISHABLE_KEY length: ${#_VITE_CLERK_PUBLISHABLE_KEY}"
        if [ -z "${_VITE_CLERK_PUBLISHABLE_KEY}" ]; then
          echo "ERROR: _VITE_CLERK_PUBLISHABLE_KEY is empty or not set!"
          echo "Please verify the substitution _VITE_CLERK_PUBLISHABLE_KEY is configured in the Cloud Build trigger"
          exit 1
        fi
        echo "DEBUG: Building Docker image with VITE_CLERK_PUBLISHABLE_KEY..."
        docker build \
          --build-arg VITE_CLERK_PUBLISHABLE_KEY="${_VITE_CLERK_PUBLISHABLE_KEY}" \
          -t ${_IMAGE_NAME} .

  # Step 2: Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

  # Step 3: Deploy to Cloud Run with environment variables and secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE_NAME}'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--no-allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:${_DEPLOY_REGION}:vega-postgres'
      - '--update-secrets'
      - 'DB_PASSWORD=DATABASE_PASSWORD:latest,CLERK_SECRET_KEY=CLERK_SECRET_KEY:latest'
      - '--update-env-vars'
      - 'SERVICE_TYPE=tenant,NODE_ENV=production,PGSSLMODE=require'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '0'

substitutions:
  # Default image name for the tenant service
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/vega-tenant'
  # Branch to build from (default: main)
  _BRANCH: 'main'
  # Clerk publishable key for frontend build (required)
  # Note: This should match the substitution name in the Cloud Build trigger
  _VITE_CLERK_PUBLISHABLE_KEY: ''
  # Service name for Cloud Run
  _SERVICE_NAME: 'vega-tenant'
  # Deployment region
  _DEPLOY_REGION: 'europe-west1'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
