steps:
  # Step 1: Build Docker image - Usiamo direttamente 'args' senza bash -c
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_CLERK_PUBLISHABLE_KEY=${_VITE_CLERK_PUBLISHABLE_KEY}'
      - '--build-arg'
      - 'VITE_MASTER_ADMIN_ID=${_VITE_MASTER_ADMIN_ID}'
      - '-t'
      - '${_IMAGE_NAME}'
      - '.'

  # Step 2: Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

substitutions:
  # Default image name for the master admin service; triggers can override this if needed
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/vega-master-admin'
  _BRANCH: 'master-admin'
  _VITE_CLERK_PUBLISHABLE_KEY: ''
  _VITE_MASTER_ADMIN_ID: ''

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
