// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'
import { SUPABASE_CONFIG, checkSupabaseConfig } from '@/config/supabase'

// Check configuration on import
checkSupabaseConfig()

export const supabase = createClient(SUPABASE_CONFIG.URL, SUPABASE_CONFIG.ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'toppery-web-app'
    }
  }
})

// Interceptor per gestire gli errori di connessione
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_OUT') {
    // Cleanup quando l'utente si disconnette
    localStorage.removeItem('lockout_username')
    localStorage.removeItem('lockout_expiry')
    localStorage.removeItem('lockout_attempts')
  }
})

export default supabase